# Generated by Django 2.0.3 on 2018-03-10 16:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WebTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('saled_num', models.IntegerField(default=0)),
                ('looked_num', models.IntegerField(default=0)),
                ('cr_date', models.DateField(auto_now_add=True)),
                ('ch_date', models.DateField(auto_now=True)),
                ('sale_price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.SaleType')),
            ],
            options={
                'ordering': ['-cr_date'],
            },
        ),
    ]
