# Generated by Django 2.0.3 on 2018-03-11 14:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180310_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('saled_num', models.IntegerField(default=0)),
                ('looked_num', models.IntegerField(default=0)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('ch_date', models.DateTimeField(auto_now=True)),
                ('sale_price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.SaleType')),
            ],
            options={
                'ordering': ['-cr_date'],
            },
        ),
    ]
