# Generated by Django 2.0.3 on 2018-03-14 07:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_logintemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintemplates',
            name='pic',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
