# Generated by Django 2.0.3 on 2018-03-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180314_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintemplates',
            name='author',
            field=models.CharField(default='菇凉佳佳佳', max_length=20),
        ),
        migrations.AddField(
            model_name='webtemplates',
            name='author',
            field=models.CharField(default='兵器太邪门', max_length=20),
        ),
    ]
