# Generated by Django 2.0.5 on 2018-05-12 15:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180327_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucaiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='菇凉佳佳佳', max_length=20, verbose_name='作者')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('pic', models.TextField(default='', verbose_name='图片地址')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('saled_num', models.IntegerField(default=0, verbose_name='已售')),
                ('looked_num', models.IntegerField(default=0, verbose_name='查看')),
                ('cr_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('ch_date', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('sale_price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.SaleType')),
            ],
            options={
                'ordering': ['-cr_date'],
            },
        ),
    ]
